name: Build and Push Docker image

on:
    push:
        branches: ["main"] # trigger on pushes to main
    workflow_dispatch: # allow manual runs

env: # single place to tweak image name
    IMAGE_NAME: 2025cloud

jobs:
    # ────────────────────────────────────────────────────────────────
    # 1. Build the image and save it as a tarball artifact
    # ────────────────────────────────────────────────────────────────
    build-image:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # QEMU + Buildx so we can build multi-arch later if we like
            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3

            # Build **but don’t push** – export to a tarball instead
            - name: Build image and export to file
              uses: docker/build-push-action@v5
              with:
                  context: .
                  tags: ${{ env.IMAGE_NAME }}:ci # local tag; will be retagged later
                  outputs: type=docker,dest=/tmp/${{ env.IMAGE_NAME }}.tar # produce a single-file OCI image

            # Hand the tarball to the next job through an artifact
            - name: Upload image artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.IMAGE_NAME }}-image
                  path: /tmp/${{ env.IMAGE_NAME }}.tar

    # ────────────────────────────────────────────────────────────────
    # 2. After a successful build, push the image to Docker Hub
    # ────────────────────────────────────────────────────────────────
    push-image:
        needs: build-image # wait for build step
        runs-on: ubuntu-latest

        steps:
            # Fetch the tarball produced in the previous job
            - name: Download built image
              uses: actions/download-artifact@v4
              with:
                  name: ${{ env.IMAGE_NAME }}-image
                  path: /tmp

            # Load it into Docker
            - name: docker load
              run: |
                  docker load --input /tmp/${{ env.IMAGE_NAME }}.tar
                  docker image ls -a

            # Enable Buildx (new Docker builder)
            - uses: docker/setup-buildx-action@v3 # for consistency

            # Login to Docker Hub
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Retag and push
            - name: Tag & push
              run: |
                  IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
                  SHA=${{ github.sha }}
                  docker tag ${{ env.IMAGE_NAME }}:ci $IMAGE:latest
                  docker tag ${{ env.IMAGE_NAME }}:ci $IMAGE:$SHA
                  docker push --all-tags $IMAGE
