name: Build Docker image

on:
    push:
        branches: ["main"] # or whatever branch you treat as source-of-truth
    workflow_dispatch: # manual trigger

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            # Enable Buildx/QEMU
            - uses: docker/setup-qemu-action@v3
            - uses: docker/setup-buildx-action@v3

            # Build **but don’t push** – export to a tarball instead
            - name: Build image and export to file
              uses: docker/build-push-action@v5
              with:
                  context: .
                  tags: 2025cloud:ci # local tag; will be retagged later
                  outputs: type=docker,dest=/tmp/2025cloud.tar # produce a single-file OCI image

            # Hand the tarball to the next workflow through an artifact
            - name: Upload image artifact
              uses: actions/upload-artifact@v4
              with:
                  name: 2025cloud-image
                  path: /tmp/2025cloud.tar
